optional param for .env file and error message

diff --git a/shell/.config/common.d/available/dotenv b/shell/.config/common.d/available/dotenv
--- a/shell/.config/common.d/available/dotenv
+++ b/shell/.config/common.d/available/dotenv
@@ -1,5 +1,10 @@
 #!/bin/bash
 
 dotenv(){
-    export $(grep -v '^#' .env | xargs -0)
+    if [ -f ${1:-.env} ]; then
+        export $(grep -v '^#' ${1:-.env} | xargs -0)
+    else
+        echo "File not found: ${1:-.env}"
+        exit 1
+    fi
 }
